var Tiles = {
    CORNER_LEFT_TOP: 0,
    CORNER_LEFT_BOTTOM: 1,
    CORNER_RIGHT_TOP: 2,
    CORNER_RIGHT_BOTTOM: 3,
    BORDER_LEFT: 4,
    BORDER_RIGHT: 5,
    BORDER_TOP: 6,
    BORDER_BOTTOM: 7,
    CLEAR: 8,
	FULL: 9
};